name: CI

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Deploy to Cluster
    steps:
      - uses: actions/checkout@master
      - name: CD
        uses: githubanotaai/simple-cd-action@master
        with:
          app_name: testapp

          deployment_repo: githubanotaai/applications
          deployment_repo_token: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}
          deployment_repo_yaml_paths: |
            applications/testapp/ENV/values.yaml
            applications/testapp123/ENV/values.yaml
            applications/testapp1234/ENV/values.yaml
          deployment_repo_yaml_imgtag_key: image.tag

          image_owner: igrowdigital
          image_repo: testapp
          image_tag: ${{ github.sha }}

          docker_build_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_build_registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_build_dockerfile_path: Dockerfile
          docker_build_context_path: .
